### PR TITLE
Fix links

### LINKED ISSUE #5: Fix all the links and buttons

### PR DESCRIPTION
**Pull request by thibaultamartin**
Closes #5 #23 #24

### CODE REVIEW

**Comment by thibaultamartin** [comment]
@HarHarLinks eyes welcome on this

**Comment by HarHarLinks** [comment]
does the privacy policy need adding to the store? pretix requires ticking a box to accept CoC and H&S right now.

**Review by HarHarLinks — APPROVED** [review]
technically, there is a link to #22 on the home page, but the content is missing.

**Comment by thibaultamartin** [comment]
Good catch for the privacy policy. Legal is on it!

**Comment by HarHarLinks** [comment]
> Good catch for the privacy policy. Legal is on it!

let's track it: #39

**Pull request merged**
